{"uuid":"236f9355-6ed2-4c20-ab6a-c2b49de7cfbf","historyId":"f9e49b2ead2ea300fff00f28453ebca","fullName":"com.selenium.ebiz.header.VerifyStaticWebsiteHelpInUtilityBarDisplayed.header_DisplayStaticWebsiteHelpInUtilityBarOnOrderHistoryPage","labels":[{"name":"package","value":"com.selenium.ebiz.header.VerifyStaticWebsiteHelpInUtilityBarDisplayed"},{"name":"testClass","value":"com.selenium.ebiz.header.VerifyStaticWebsiteHelpInUtilityBarDisplayed"},{"name":"testMethod","value":"header_DisplayStaticWebsiteHelpInUtilityBarOnOrderHistoryPage"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"com.selenium.ebiz.header.VerifyStaticWebsiteHelpInUtilityBarDisplayed"},{"name":"host","value":"W7VDIHPQC16WPL"},{"name":"thread","value":"12160@W7VDIHPQC16WPL.PoolService-0(11)"}],"links":[],"name":"header_DisplayStaticWebsiteHelpInUtilityBarOnOrderHistoryPage","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [true] but found [false]","trace":"java.lang.AssertionError: expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:93)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:512)\r\n\tat org.testng.Assert.assertTrue(Assert.java:41)\r\n\tat org.testng.Assert.assertTrue(Assert.java:51)\r\n\tat com.selenium.ebiz.header.VerifyStaticWebsiteHelpInUtilityBarDisplayed.header_DisplayStaticWebsiteHelpInUtilityBarOnOrderHistoryPage(VerifyStaticWebsiteHelpInUtilityBarDisplayed.java:105)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:661)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)\r\n\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)\r\n\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n"},"stage":"finished","start":1574865206150,"stop":1574865221385,"parameters":[{"name":"arg0","value":"chrome"},{"name":"arg1","value":"74.0"},{"name":"arg2","value":"Windows 10"},{"name":"arg3","value":"public void com.selenium.ebiz.header.VerifyStaticWebsiteHelpInUtilityBarDisplayed.header_DisplayStaticWebsiteHelpInUtilityBarOnOrderHistoryPage(java.lang.String,java.lang.String,java.lang.String,java.lang.reflect.Method) throws java.lang.Exception"}]}